name: Run Cypress Tests and Build Docker Image

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main  # Trigger on successful merge to main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 2004THun
          POSTGRES_DB: todo_db
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Set up Docker Compose
        run: docker compose up -d --build

      - name: Wait for backend to be ready
        run: |
          echo "Waiting for backend..."
          until curl -s http://localhost:5000/health; do
            sleep 2
          done

      - name: Init DB
        run: docker compose exec -T backend python app/init_db.py

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: tests
          install: true
          start: npm run cy:run
          wait-on: http://localhost:5000
          wait-on-timeout: 60

  build-and-push-image:
    runs-on: ubuntu-latest
    needs: cypress-tests  # Only run if tests pass
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=$(echo ${GITHUB_SHA::7})" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT}}

      - name: Set lowercase image owner
        run: echo "OWNER_LC=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: "Debug: print image tag"
        run: |
          echo "OWNER_LC: ${{ env.OWNER_LC }}"
          echo "Final image tag 1: ghcr.io/$OWNER_LC/todo-app:latest"
          echo "Final image tag 2: ghcr.io/$OWNER_LC/todo-app:${{ env.IMAGE_TAG }}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./backend  # or ./backend depending on where your Dockerfile is
          file: ./backend/Dockerfile  # or ./backend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/todo-app:latest
            ghcr.io/${{ env.OWNER_LC }}/todo-app:${{ env.IMAGE_TAG }}
