name: Run Cypress Tests

on:
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 2004THun
          POSTGRES_DB: todo_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: docker-compose up -d --build

      - name: Wait for backend to be ready
        run: sleep 10  # or healthcheck + wait-for-it.sh

      - name: Init DB
        run: docker-compose exec backend python app/init_db.py

      - name: Run Cypress Tests
        run: npm run cy:run

      - name: run cypress
        run: npm run test:e2e
